#!/bin/zsh
local name=$1 url=$2 branch=$3
local src=$FFSRC/$name build=$FFBUILD/$name
if [[ ! -d $src ]] {
    git clone --mirror $url $src
} else {
    git -C $src fetch --all -p
}

(( $+RESET )) && rm -rf $build
if [[ ! -d $build ]] {
    git clone $src $build -b $branch
} else {
    git -C $build pull
}
